import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Script from "next/script";
import ReduxProvider from "@/store/provider";  

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
          crossOrigin="anonymous"
        />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider> 
          <nav className="navbar navbar-expand-lg bg-primary-subtle fw-bolder p-3 shadow " style={{ textShadow: "1px 1px 1px  grey" }}>
            <div className="container-fluid">
              <Link className="navbar-brand " href="/">
                Home
              </Link>

              <button
                className="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span className="navbar-toggler-icon"></span>
              </button>

              <div className="collapse navbar-collapse" id="navbarSupportedContent">
                <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                  
                  <li className="nav-item navbar-brand">
                    <Link className="nav-link " href="/props">Props</Link>
                  </li>
                  <li className="nav-item navbar-brand">
                    <Link className="nav-link " href="/about">About</Link>
                  </li>
                  
                  <li className="nav-item navbar-brand">
                    <Link className="nav-link " href="/getAllPrisma">PrismaDB</Link>
                  </li>
                  <li className="nav-item navbar-brand">
                    <Link className="nav-link " href="/components/fetchUser">PrismaAPI</Link>
                  </li>
                  <li className="nav-item navbar-brand">
                    <Link className="nav-link " href="/contact">
                      Contact
                    </Link>
                  </li>
                  <li className="nav-item navbar-brand">
                    <Link className="nav-link " href="/contactList">
                      Contact List
                    </Link>
                  </li>


                  <li className="nav-item dropdown navbar-brand ">
                    <a className="nav-link dropdown-toggle " href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Hooks
                    </a>
                    <ul className="dropdown-menu">
                      <li><Link className="dropdown-item " href="/counter">useState</Link></li>
                      <li><Link className="dropdown-item" href="/useContext">useContext</Link></li>
                      <li><Link className="dropdown-item" href="/usereducer">useReducer</Link></li>
                      <li><Link className="dropdown-item" href="/useeffect">useEffect</Link></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>

          <div className="container-fluid">
            <div className="row">
              <div className="col pt-4">{children}</div>
            </div>
          </div>
        </ReduxProvider>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossOrigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.min.js" integrity="sha384-7qAoOXltbVP82dhxHAUje59V5r2YsVfBafyUDxEdApLPmcdhBPg1DKg1ERo0BZlK" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}
